PRAGMA foreign_keys = ON;

-- Dog toothbrush category: 50 public dog-owner experiences
INSERT OR IGNORE INTO products (id, name, category, active) VALUES ('mindup-small-head', '犬口ケア 歯ブラシ スモールヘッド', 'dog-toothbrush', 1);
INSERT OR IGNORE INTO products (id, name, category, active) VALUES ('mindup-small-soft', '犬口ケア 歯ブラシ スモールヘッド ソフト', 'dog-toothbrush', 1);
INSERT OR IGNORE INTO products (id, name, category, active) VALUES ('petkiss-compact', 'PETKISS デンタルブラシ コンパクト', 'dog-toothbrush', 1);
INSERT OR IGNORE INTO products (id, name, category, active) VALUES ('petkiss-finger', 'PETKISS 指サック歯ブラシ', 'dog-toothbrush', 1);
INSERT OR IGNORE INTO products (id, name, category, active) VALUES ('mindup-large-head', '犬口ケア 歯ブラシ ラージヘッド', 'dog-toothbrush', 1);
INSERT OR IGNORE INTO products (id, name, category, active) VALUES ('mindup-slim-cylinder', '犬口ケア 歯ブラシ スリムシリンダーヘッド', 'dog-toothbrush', 1);

DELETE FROM reviews WHERE product_id IN ('mindup-small-head', 'mindup-small-soft', 'petkiss-compact', 'petkiss-finger', 'mindup-large-head', 'mindup-slim-cylinder');

INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'scared gentle', '小さめヘッドで磨きやすく、犬もそれほど嫌がらずに磨かせてくれたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'gentle', 'ブラシはやわらかく歯ぐきに当てやすい一方、5.4kgの愛犬にはヘッドが小さすぎて磨きにくかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'scared daily', '小さいヘッドと握りやすい柄で奥歯まで届き、歯ブラシ嫌いの犬でも以前より長く磨けて毎日の習慣にしやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', 'トイプードル', NULL, NULL, 'daily', 'ヘッドが小さく、トイプードルの奥歯や歯の側面まで磨きやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', 'ミニチュアダックス 2頭', NULL, NULL, 'scared', '指にはめるタイプでは難しかった1頭も磨け、小さく細いヘッドで奥まで届きやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '小さめヘッドで奥歯まで届きやすく、扱いやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'daily', '小さいヘッドで奥に入れやすく、歯磨きが好きではない犬でも短時間で済ませやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', 'チワワ', NULL, NULL, NULL, '赤ちゃん用歯ブラシと比べてヘッドサイズは近かったが、持ち手は犬用の方が持ちやすいと感じたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', 'チワワ', NULL, NULL, 'daily', '先住のチワワに毎日使用。一般的な歯ブラシより口に入りやすく、小さな口でも使いやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', 'パピヨン', NULL, NULL, NULL, '口の小さいパピヨンでも奥まで届き、ヘッドサイズが合っていたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '想像よりヘッドは大きめに感じたが、歯に当たる面積と柄のカーブで力が入りすぎず磨きやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '持ち手が長く、先端のブラシが小さいため奥歯へ入れやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, 'small', NULL, 'chewing', '小型犬にはヘッドが合っていたが、噛むため毛先が開きやすく交換頻度が高かったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '先端が小さく角度も付いているため、手元を動かしやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '大きい歯ブラシでは届きにくい歯のすき間の食べ残しを、小さなヘッドで取りやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', 'トイプードル', NULL, NULL, NULL, 'トイプードルに使用し、奥歯までしっかり磨けたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'puppy', '子犬の小さな歯でもヘッドが当てやすく、扱いやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '小さいヘッドで奥まで磨け、持ち手も握りやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '奥歯まで磨きやすく、使いやすさ・安全性・耐久性にも満足したという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'scared', 'ヘッドは小さく使いやすかったが、犬自身は歯磨きを嫌がったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'daily', '小さいヘッドで細かく磨きやすく、できるだけ毎日続けているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, 'gentle', '歯の手術後はソフトを使っていたが、状態が落ち着いて通常タイプへ戻すと、よりしっかり磨ける感触があったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, NULL, NULL, NULL, '久しぶりに購入し、やはり小さいヘッドは磨きやすいと感じたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', 'チワワ 3歳', NULL, NULL, 'daily', '3歳のチワワに毎日使い、定期的に新しいブラシへ交換しながら継続しているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-head', NULL, 'small', NULL, NULL, '小型犬の口にも入れやすく、磨きやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/208496_10001972/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', NULL, NULL, NULL, 'gentle scared', '毛が柔らかく、犬が嫌がらずに磨かせてくれたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', 'ポメラニアン 3kg', NULL, NULL, 'gentle scared', '3kgのポメラニアンに使用。通常の硬さは嫌がるが、ソフトはじっとしやすく奥歯まで磨けたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', NULL, NULL, NULL, 'senior scared gentle', '7歳から本格的に歯磨きを再開。柔らかいブラシで、嫌がりながらも慣らしているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', NULL, NULL, NULL, 'gentle', '薄いヘッドで奥まで入れやすく、使いやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', NULL, NULL, NULL, 'senior gentle', '口の小さなシニア犬で、歯ぐきへの負担を考えてソフトタイプを継続使用しているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', NULL, NULL, NULL, 'scared beginner', '最初は嫌がったため、少しずつ慣らしながら使っているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', NULL, NULL, NULL, 'senior scared gentle', '高齢で歯ぐきが弱く歯磨きも嫌がるため、負担の少ないソフトタイプを選んだという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', 'チワワ', NULL, NULL, 'gentle', 'チワワの口にヘッドサイズが合い、ソフトタイプを初めて選んだという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', '柴犬 9.5kg', NULL, NULL, NULL, '9.5kgの柴犬にはヘッドが少し小さく感じたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-small-soft', NULL, NULL, NULL, 'gentle', '柔らかさは少し物足りなく感じたものの、小さいヘッドを仕上げ用として使っているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10013820/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-compact', 'トイプードル 3.5kg', NULL, NULL, NULL, '口が小さい3.5kgのトイプードルで、このコンパクトヘッドが最も磨きやすくリピートしているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/261122_10961289/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-compact', 'トイプードル', NULL, NULL, NULL, '口の小さいトイプードルで、奥まで届いて磨きやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/261122_10961289/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-compact', 'トイプードル 3.7kg', NULL, NULL, NULL, '3.7kgのトイプードルで、大きく厚いブラシより小さなヘッドの方が磨きやすく、こちらへ戻ったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/261122_10961289/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-compact', 'トイプードル 4kg', NULL, NULL, NULL, '4kgのトイプードルで、口が小さいためコンパクトなヘッドがちょうどよかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/261122_10961289/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-compact', '子犬', NULL, NULL, 'puppy', '小さなヘッドで子犬の口にも入りやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/261122_10961289/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-finger', 'チワワ', NULL, NULL, 'scared', 'チワワに使用し、ヘッドの厚さ・毛の硬さ・長さが合ってしっかり磨けたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/review/review/item/1/261122_10599798/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-finger', 'トイプードル 約3kg', NULL, NULL, 'chewing', '約3kgの口の小さいプードルで奥歯まで届き、噛まれてもシリコン部分が指を守ってくれたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/review/review/item/1/261122_10599798/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-finger', 'テリア 10kg', NULL, NULL, NULL, '10kgのテリアで、見えにくい上の奥歯も小さなヘッドで細部まで磨きやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/review/review/item/1/261122_10599798/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-finger', NULL, NULL, NULL, 'scared', '犬は嫌がるものの、比較的すみずみまで磨きやすかったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/review/review/item/1/261122_10599798/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-finger', 'ヨークシャーテリア', NULL, NULL, NULL, 'ヨーキーで、指に装着して磨ける点が便利だったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/review/item/1/219837_10023011/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('petkiss-finger', 'ゴールデンレトリバー', NULL, NULL, 'daily', '大型のゴールデンレトリバーに毎晩使用し、指先で操作しやすい点に満足したという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/review/item/1/219837_10023011/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-large-head', NULL, NULL, NULL, 'senior scared speed', '歯磨きが大嫌いな老犬で、少し大きめのヘッドなら短時間で汚れを落としやすそうだと感じたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/210982_10002326/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-large-head', NULL, NULL, NULL, 'scared', '薄いヘッドで奥歯まで届きやすく、歯磨きを嫌がる犬でも以前より受け入れてくれたという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/210982_10002326/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-large-head', NULL, NULL, NULL, 'scared', '歯ブラシ自体には問題なかったが、犬が歯磨きを嫌がるため慣らしが必要だったという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/210982_10002326/1.1/');
INSERT INTO reviews (product_id, dog_breed, dog_size, coat_type, needs, summary, source_type, source_url) VALUES ('mindup-slim-cylinder', 'チワワ 3kg', NULL, NULL, 'chewing', '3kgのチワワで超小型犬用を噛み壊したため一回り大きいスリムシリンダーを試し、優しく噛みながら使えているという体験。', 'public_purchase_review_summary', 'https://review.rakuten.co.jp/item/1/216162_10026612/1.1/');

-- Verification queries
SELECT COUNT(*) AS toothbrush_product_count FROM products WHERE category='dog-toothbrush' AND active=1;
SELECT COUNT(*) AS toothbrush_review_count FROM reviews r JOIN products p ON p.id=r.product_id WHERE p.category='dog-toothbrush';
