-- 犬用ハーネス（dog-harness）カテゴリの新規追加。追加のみ（既存の商品・口コミは変更しない）。
-- 口コミは楽天市場・Yahoo!ショッピングの購入者レビューと公開動画の説明文を要約したもの（原文の転載なし）。Amazonレビューは使用していない。
-- 犬種・サイズ・毛の長さ・性格は出典に書かれている場合のみ記録し、不明な項目は NULL のままにしている。
-- 再実行しても重複しない（商品は INSERT OR IGNORE、口コミは同一商品・同一要約があれば挿入しない）。
PRAGMA foreign_keys = ON;

INSERT OR IGNORE INTO products (id, name, category, affiliate_url, active) VALUES ('julius-k9-idc-power', 'Julius-K9 IDCパワーハーネス', 'dog-harness', 'https://www.amazon.co.jp/s?k=Julius-K9+IDCパワーハーネス&tag=100things-22', 1);
INSERT OR IGNORE INTO products (id, name, category, affiliate_url, active) VALUES ('ruffwear-front-range', 'ラフウェア フロントレンジハーネス', 'dog-harness', 'https://www.amazon.co.jp/s?k=ラフウェア+フロントレンジハーネス&tag=100things-22', 1);
INSERT OR IGNORE INTO products (id, name, category, affiliate_url, active) VALUES ('puppia-soft-vest', 'PUPPIA ソフトベストハーネス', 'dog-harness', 'https://www.amazon.co.jp/s?k=パピア+ソフトベストハーネス&tag=100things-22', 1);
INSERT OR IGNORE INTO products (id, name, category, affiliate_url, active) VALUES ('petsafe-easy-walk', 'PetSafe イージーウォークハーネス', 'dog-harness', 'https://www.amazon.co.jp/s?k=イージーウォークハーネス+PetSafe&tag=100things-22', 1);
INSERT OR IGNORE INTO products (id, name, category, affiliate_url, active) VALUES ('curli-vest-air-mesh', 'Curli ベストエアメッシュハーネス', 'dog-harness', 'https://www.amazon.co.jp/s?k=curli+ベストエアメッシュハーネス&tag=100things-22', 1);
INSERT OR IGNORE INTO products (id, name, category, affiliate_url, active) VALUES ('hakusan-zero-harness', 'Hakusan ゼロハーネス', 'dog-harness', 'https://www.amazon.co.jp/s?k=Hakusan+ゼロハーネス&tag=100things-22', 1);

WITH new_reviews(product_id,dog_breed,dog_size,coat_type,needs,summary,source_type,source_url) AS (
VALUES
('julius-k9-idc-power','柴犬',NULL,NULL,'sizing','体重12kg台後半で胴が長めの柴犬にMiniを選び、ベルトを調整してぴったり合わせられた。リードを付ける部分の強度だけは少し気になったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/1.1/'),
('julius-k9-idc-power','柴犬',NULL,NULL,'escape sizing','首輪だけだと抜けやすい柴犬（9kg）にMiniがちょうど合い、歩き方に癖があっても問題なく散歩できている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/1.1/'),
('julius-k9-idc-power','柴犬',NULL,NULL,'durability easy-on','8歳の柴犬で、迎えた時から同じシリーズを使い続けている。着脱が簡単で不具合もなく、気づくと数年使えているという長期使用の体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/1.1/'),
('julius-k9-idc-power','豆柴',NULL,NULL,'easy-on sizing','頭からかぶせるだけで着けられるので嫌がらずに装着できたが、7kg弱の豆柴にはMiniが少し大きかったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/1.1/'),
('julius-k9-idc-power',NULL,NULL,NULL,'puppy chew durability','子犬の頃に1本目を噛んで壊してしまったが、買い直した2本目は約6年使えたというリピート購入の体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/1.1/'),
('julius-k9-idc-power','フレンチブルドッグ2頭',NULL,NULL,'multi escape','9kgと10kgのフレブル2頭ともMiniで合ったが、調整部分が緩んでいた時に散歩中に引っ張られて抜けたことがあり、こまめな確認が必要と感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/2.1/'),
('julius-k9-idc-power','柴犬',NULL,NULL,'pull trachea','首輪では引っ張った時にゼイゼイと苦しそうだった5歳の柴犬（9kg弱）が、このハーネスに替えてからは苦しそうな様子がなくなった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/2.1/'),
('julius-k9-idc-power','ジャックラッセルテリア',NULL,NULL,'trachea','気管が細く首輪も一般的なハーネスでも咳き込んでいたジャックラッセルで、前側に少し余裕を持たせて胸下を合わせたところ、抜けずに咳もほとんど出なかった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/2.1/'),
('julius-k9-idc-power','トイプードル',NULL,NULL,'pull trachea sizing','引っ張り癖と軽い気管虚脱がある4.8kgのトイプードルにMiniMiniを最小に調整して使用。胸側のベルトは余り気味だが、最初は気にしていたベルトにもすぐ慣れた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/3.1/'),
('julius-k9-idc-power','雑種',NULL,NULL,'escape durability','洗濯機で洗っても留め具やほつれの問題は出ていないが、犬が急に後ろへ下がると簡単に抜けることがあり、先代犬（雑種14kg）は一度抜けたため首輪との併用を考えた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/3.1/'),
('julius-k9-idc-power','柴犬',NULL,NULL,'escape','2歳の柴犬（10kg）で3本目になるほど丈夫だと感じている一方、後ずさりすると抜けてしまうため首輪と連結して使っている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/3.1/'),
('julius-k9-idc-power',NULL,NULL,NULL,'durability skin','約1年半でリード金具をつなぐ部分が半分近く裂け、擦れる部分の毛も抜けてきたが、夏に別のハーネスへ替えると犬が全く歩かず、結局これに戻した体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/3.1/'),
('julius-k9-idc-power','ジャックラッセルテリア2頭',NULL,NULL,'senior multi trachea','シニアになり興奮して首輪で喉を締めるのを避けたくて、6kgのジャックラッセル2頭に購入。別売りのチェストパッドの付け方は分かりにくかったが、一度付ければ装着は簡単だった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/3.1/'),
('julius-k9-idc-power',NULL,NULL,NULL,'mobility handle','後ろ足が弱い犬で、リードの位置が背中寄りのため引いた時の前足への負担が減ったように感じ、排泄時にふらつく時は持ち手で体を支えられて便利だった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000922/2.1/'),
('julius-k9-idc-power',NULL,'large',NULL,'skin durability','40kgの大型犬で約3年使えている。脇が少し擦れるのは他のハーネスでも避けにくいと感じつつ、夜は大きな反射部分が見やすいという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/1.1/'),
('julius-k9-idc-power','ラブラドールレトリバー',NULL,NULL,'scared escape sizing','首輪が外れて逃げたことがある怖がりのラブラドール（26kg）に、体重表を基準にサイズ1を選んでぴったり合い、抜ける心配がなさそうだと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/1.1/'),
('julius-k9-idc-power',NULL,'medium',NULL,'pull trachea','引っ張りの強い中型犬で、首輪やY字型のハーネスでもゼイゼイしていたが、このハーネスでは喉元に当たらず苦しそうな音がしなくなった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/1.1/'),
('julius-k9-idc-power','ダルメシアン',NULL,NULL,'pull trachea','力が強く引っ張る30kgのダルメシアンで、コントロールしやすくなり、首の締め付けがなくなってゼイゼイ言わなくなった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/1.1/'),
('julius-k9-idc-power','ボーダーコリー',NULL,NULL,'pull easy-on','訓練所では首輪だけだった15.8kgのボーダーコリーが、自分から頭を出して着けさせるほど気に入り、引っ張り癖もほとんど出なくなった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/1.1/'),
('julius-k9-idc-power','ラブラドール',NULL,NULL,'mobility','足腰が弱り首輪で足を滑らせることがあった13歳のラブラドールに使い、本人も快適そうで、もっと早く替えればよかったと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/2.1/'),
('julius-k9-idc-power','ラブラドール',NULL,NULL,'dislike-on sizing','1歳のラブラドールにサイズ2を選んだら首のストラップが余った。重さと大きさがあるためか装着時はテーブルの下に隠れて固まるが、着ければ散歩を喜ぶという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/2.1/'),
('julius-k9-idc-power',NULL,NULL,NULL,'escape skin','装着は1か所留めるだけで簡単だが、後ろに引っ張られると抜けたことがあり、脇の下が擦れて毛玉ができたという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/2.1/'),
('julius-k9-idc-power','コーギー',NULL,NULL,'skin','前のハーネスで脇や胸が赤くなっていた16kgのコーギーに使い、説明書どおりに着けると脇とベルトが離れて擦れず、引っ張られた時も安定している体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/2.1/'),
('julius-k9-idc-power','ラブラドールハーフ',NULL,NULL,'escape','やせ型22kgのラブラドールハーフにサイズ1。胸のベルトを一番短くしてちょうど良いが、前にまっすぐ引かれた時に抜けるのが不安で首輪と2本のリードで使っている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/2.1/'),
('julius-k9-idc-power','ジャーマン・シェパード',NULL,NULL,'puppy handle','9か月・30kgのシェパードで、持ち手のおかげで飛びつきや急な引っ張りを抑えやすくなった。一方、むき出しのバックルが塀に擦れて壊れないか心配という体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/208747_10000923/2.1/'),
('julius-k9-idc-power','甲斐犬',NULL,NULL,'sizing dislike-on','胸だけが大きい甲斐犬でサイズ選びに苦労したが、サイズ0で合い、足を通すタイプと違って嫌がらずに着けられている体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=tsumugu-design-goods&page_key=harness-03'),
('julius-k9-idc-power',NULL,NULL,NULL,'pull escape','引っ張り癖のある犬で喉元への食い込みは減ったと感じる一方、思い切り後ろに下がると簡単に抜けること、雨上がりはお腹側が乾きにくいことが気になった体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=tsumugu-design-goods&page_key=harness-03'),
('julius-k9-idc-power','柴犬',NULL,NULL,'handle escape','3.9kgの柴犬でも緩くならずに使え、ドッグランで捕まえる時に持ち手が便利。ただし強く引かれた時や持ち手で抱き上げた時に抜けることがあると注意している体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=flaner-y&page_key=f10021127'),
('julius-k9-idc-power','黒柴',NULL,NULL,'sensitive dislike-on','とても神経質な7.2kgの黒柴にMiniを用意し、装着しやすく安定感もあると感じたが、何度か試しても慣れることができず使用を断念した体験（動画）。','public_experience_summary','https://www.youtube.com/watch?v=4znCzt_MxUo'),
('ruffwear-front-range','ラブラドール',NULL,NULL,'pull trachea','興奮すると強く引っ張り首輪だけでは喉を圧迫していた2歳のラブラドール（21kg）で、体をしっかり支えつつ当たりが柔らかく、価格に見合うと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range',NULL,NULL,NULL,'puppy pull','生後6か月ほどの元野犬（15.5kg）にSサイズを合わせ、胸側のループにリードを付けると引っ張りが少し軽くなったと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','トイプードル',NULL,NULL,'escape clothes','まだ若く散歩中にちょろちょろ動く4.7kgのトイプードルにXXSがぴったりで、調整して冬服の上からでも着けられた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','パグ',NULL,NULL,'stiff','9kgちょっとのパグにXSを選び、サイズにはまだ余裕があるがパッド部分が硬く感じたという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','ビションフリーゼ',NULL,NULL,'puppy easy-on','6.5か月のビションで丈夫さには安心したが、頭を通す前にアジャスターを緩め、通した後に締め直す作業が毎回面倒だったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','柴犬',NULL,NULL,'dislike-on','3.4kgの柴犬にXXSを着けたところ、前のハーネスより重く感じたのか固まって動けず、少しずつ慣らしているという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','ボーダーコリー',NULL,NULL,'escape sizing outdoor','山歩きで何度使っても抜けたことがない。同じ17kgでも、毛量が少なく細身の子はS、胸ががっしりした子はMと、体格でサイズが分かれた多頭飼いの体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','パグ',NULL,NULL,'skin','劣化したハーネスで皮膚が赤くなったパグ（8.7kg）に替え、当たりが柔らかく、名前欄や迷子札入れ、ライト用の輪など機能が多くて便利だった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','柴犬',NULL,NULL,'escape','前足が細長く頭が小さいため首輪もひも状のハーネスも抜けやすかった10kgの柴犬で、探した末にこれに落ち着きリピートしている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/1.1/'),
('ruffwear-front-range','ミニチュアシュナウザー',NULL,NULL,'puppy pull trachea dislike-on','引っ張り癖でいつもゼーゼーしていた9か月のシュナウザー。人気の別製品は断固拒否したが、これは怪訝な顔をしつつも散歩に行け、引っ張る回数も減った体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range','柴犬',NULL,NULL,'puppy escape','引っ張りと後ずさりがあり他のハーネスでは何度も抜けた7か月の柴犬（9.6kg）で、何度後ずさりしても抜けなかった。首回りの調整が毎回必要な点は面倒という体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range','豆柴',NULL,NULL,'puppy sensitive','いつもと違うことに敏感な9か月の豆柴で、ハーネスだけならドッグランで楽しく走れたが、リードを付けると転げ回って鳴き、リードの金具音も気にしていた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range','ゴールデンレトリバー',NULL,NULL,'pull skin','胸毛が多い34kgのゴールデンにL/XLを選び、引っ張り抑制用の前側ループにリードを付けると引っ張りがかなり減り、パッドのおかげで擦れの心配もない体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range',NULL,NULL,NULL,'stiff escape','8kg弱の小型犬にはコルセットのように硬く、特に肩まわりがごわつくため一部を外して工夫したが、その硬さのおかげで急にバックしても抜けないと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range','秋田犬',NULL,NULL,'outdoor','顔が大きい40kgの秋田犬で、肩まわりを合わせると頭が入りにくいが少し緩めても抜けなさそう。キャンプで数日着けっぱなしでも当たりが優しいという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range',NULL,NULL,NULL,'escape','着けた初日は戸惑った顔だったが翌日には慣れた。ただ前足を踏ん張った状態で前に引いたら抜けてしまい、ベルトを合わせ直したという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range',NULL,NULL,NULL,'scared escape outdoor','人慣れしない元野犬（14kg）に使い、びっくりして後ずさりしても抜けず、迎えて2年でようやく野山を楽しめるようになった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/2.1/'),
('ruffwear-front-range',NULL,NULL,NULL,'escape sizing','トリミングで毛が短くなりJulius-K9が抜けやすくなったため替えたところ、H型で抜けにくく喉も締めないが、止まった状態で合わせても歩くと緩むなどサイズ調整は難しかった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/3.1/'),
('ruffwear-front-range','トイプードル2頭',NULL,NULL,'multi escape','3.5kgと5.2kgのトイプードルにXXSとXSを使い、首回りが少し大きくても後ろに引かれて抜けることはなく、迷子札入れや名前欄も便利だった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/266503_10000952/3.1/'),
('ruffwear-front-range','フレンチブルドッグ',NULL,NULL,'neck pull','頸椎のヘルニアがあり首に負担をかけたくない8.6kgのフレブルで、前側の引っ張り防止リングも使える一方、首が太く毎回サイズ調整が必要で価格も高めと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=torusdogmartyokohama&page_key=ruffwear-frontrange-harness'),
('ruffwear-front-range','ジャックラッセルテリア',NULL,NULL,'skin pull','以前のハーネスで引っ張ると首の下が赤くなり毛も抜けた5.6kgのジャックラッセルに替え、安定感があると感じたが、バックルは硬めで慣れるまで扱いにくかった体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=torusdogmartyokohama&page_key=ruffwear-frontrange-harness'),
('ruffwear-front-range','柴犬',NULL,NULL,'senior trachea','シニアになり首輪だけでは喉に負担がかかると考えて10歳の柴犬（11kg）に使用。頭を通す部分はやや狭いが、その分抜けにくいと感じている体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=torusdogmartyokohama&page_key=ruffwear-frontrange-harness'),
('ruffwear-front-range','アメリカンコッカースパニエル',NULL,NULL,'pull','気になる犬や鳥を見ると突然ダッシュし、前年に引っ張られて大けがをした11kgのアメリカンコッカーで、ようやく合うハーネスが見つかったと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=torusdogmartyokohama&page_key=ruffwear-frontrange-harness'),
('ruffwear-front-range','ミニチュアシュナウザー',NULL,NULL,'dislike-on','しつけ用のハーフチョークから替え、最初は嫌がったものの慣れると落ち着いて着けられるようになったミニチュアシュナウザーの体験（動画）。','public_experience_summary','https://www.youtube.com/watch?v=dw-hQHkfn3Q'),
('ruffwear-front-range','秋田犬',NULL,NULL,'durability outdoor','迎えてから3年間ずっと同じハーネスを使い続け、キャンプにも連れて行っている秋田犬の長期使用の体験（動画）。','public_experience_summary','https://www.youtube.com/watch?v=yo-DWYU8VzQ'),
('puppia-soft-vest','ミニチュアダックスフンド',NULL,NULL,'mobility easy-on','足元が少しふらつく17歳・3.7kgのミニチュアダックスで、着脱が簡単なのが助かった。Mでは少し大きかったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','カニンヘンダックスフンド',NULL,NULL,'sizing clothes','胴回り36cm・4.5kgのカニンヘンダックスで、服の上から用のLは大きすぎ、服なし用のMはベルトに余裕がなくマジックテープで緩められなかった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest',NULL,NULL,NULL,'trachea','気管虚脱があり、メガネ型のハーネスではえずいていたが、気管に当たる布地が広いこのタイプに替えて少し楽になった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','ミニチュアシュナウザー',NULL,NULL,'puppy escape sizing','7か月・7.3kgのシュナウザーにXLを選んだら一番締めても胸が浮き、トリミング後はさらに緩く、自転車に興奮した時に脱げてしまった。Lにすべきだったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','チワワ・日本テリア',NULL,NULL,'multi chew','チワワは経年劣化で買い替える程度に長持ちした一方、日本テリアは少し噛んだだけで噛み破ってしまったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','ポメラニアン×チワワ',NULL,NULL,'puppy escape','4か月・2kg未満の子犬にSを着けたところ、1週間で何度か脱げてしまい、XSの買い足しを考えている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','ボストンテリア',NULL,NULL,'pull','かなり引っ張る3歳のボストンテリアでも外れたことはなく洗えて便利だが、抜け毛がよく付き、においも付きやすいという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','シュナプー',NULL,NULL,'escape','6.5kgのシュナプーにXL。前足を入れる穴が大きく散歩中に一度抜けたが、マジックテープをきつめに調整し直してからは抜けていない体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest',NULL,NULL,NULL,'escape','色違いで4つ目のリピート。サイズが大きいと踏ん張った時に首から抜けるので、苦しくない範囲できつめに着けている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest',NULL,NULL,NULL,'pull noise sensitive','グイグイ歩く12kgの犬でXLは小さくXXLに交換。首元の圧迫が少ない一方、強力なマジックテープを外す音に音に敏感な犬が少し驚くという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','トイプードル',NULL,NULL,'noise sizing','7kgのトイプードルにXLは少し大きかった。マジックテープのバリバリ音を嫌がって暴れたが、ゆっくり少しずつはがすと大丈夫になった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/1.1/'),
('puppia-soft-vest','パピヨン',NULL,NULL,'puppy noise','5か月・2.8kgのパピヨンにSがちょうど良く、マジックテープを外す音には一瞬驚いていたという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/2.1/'),
('puppia-soft-vest',NULL,NULL,NULL,'neck','首のヘルニアになった犬で、首に負担がかかりにくい形として選び、治療で散歩に行けるようになってからも嫌がらずに使えている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/2.1/'),
('puppia-soft-vest',NULL,NULL,NULL,'chew','ひも状のハーネスはどうしても噛んでしまう3.2kgの犬で、体にフィットするベストタイプにしたらすんなり散歩に行けた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/2.1/'),
('puppia-soft-vest',NULL,NULL,NULL,'durability','体にぴったり合って抜けずに使えているが、使ううちにマジックテープが効きにくくなるので消耗品として買い替えているという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/230805_10000752/2.1/'),
('puppia-soft-vest','トイプードル',NULL,NULL,'sizing','首回り21cm・胴回り36cmの華奢なトイプードルで、Sは胴がきつくMにしたらあご下に余裕ができた。背中のマジックテープで首回りを詰めて使っている体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=best-friends&page_key=puppia-harness002'),
('puppia-soft-vest',NULL,NULL,NULL,'puppy scared escape noise','人や音に怯える3〜4か月の元野犬の子犬でLは大きく、マジックテープの音にも怖がる。一度すり抜けたので、ハーネスだけの散歩は避けた方がよいと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=best-friends&page_key=puppia-harness002'),
('puppia-soft-vest','ポメラニアン',NULL,NULL,'sizing','4歳・4kgのポメラニアンで、トリミング前の毛量が多い時期用のLは抜けないか少し不安、Mはきつめだが安心感があるという体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=best-friends&page_key=puppia-harness002'),
('puppia-soft-vest','ミニチュアダックスフンド',NULL,'long',NULL,'胸が前に張っていない4.6kgのロングのミニチュアダックスに合い、軽くて洗ってもすぐ乾くので色違いで買い足した体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=best-friends&page_key=puppia-harness002'),
('puppia-soft-vest','ロングコートチワワ2頭',NULL,'long','multi dislike-on','2.2kgと1.6kgのロングコートチワワにSとXS。軽く、着脱を嫌がる犬でも着けやすく、首への負担も少ないと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=best-friends&page_key=puppia-harness002'),
('puppia-soft-vest','ミニチュアピンシャー',NULL,NULL,'clothes sizing','2.8kgのミニピンにM。首回りは大きいが脱げることはなさそうで、冬のアウターの上からも使えそうだという体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=best-friends&page_key=puppia-harness002'),
('petsafe-easy-walk',NULL,NULL,NULL,'pull skin','以前使っていたデラックス版より肌当たりが気になり、服を着せずに使うと赤くなる。ただ他のものに替えると引っ張ってしまうので使い続けているという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','シベリアンハスキー',NULL,NULL,'pull skin','チョーカーで散歩していた23kgのハスキーで、引っ張る力が半分ほどになった一方、脇が擦れて血が出たため当て布を考えたという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','ラブラドール4頭',NULL,NULL,'pull multi','引っ張られて捻挫や転倒を繰り返していたラブラドール4頭の家庭で、着けると引っ張らなくなり、1人で4頭の散歩もできそうだと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','ダックスフンド',NULL,NULL,'pull','しつけ教室でも直らなかった4.3kgのダックスの引っ張りが、着けた途端に止まり驚いたという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','柴犬',NULL,NULL,'pull','トレーナーに勧められて使っている10kgの柴犬で、引っ張り癖自体は直らないが散歩はしやすくなったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','ゴールデンドゥードル',NULL,NULL,'pull reactive','8歳になりほとんど引っ張らなくなったが、吠えられると向かっていってしまう42kgのゴールデンドゥードルのため手放せないという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','コーギー',NULL,NULL,'pull sizing','引っ張りの強い9kgのコーギーで、持っているJulius-K9より引っ張り対策には効果がありそうと感じた。サイズの境目で小さい方を選び、少し小さかった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk',NULL,'small',NULL,'pull escape scared','腰の手術後の家族と歩くために購入し、引く力がほとんどかからなくなった。ただ4kgの小型犬で、胸下のひもを短くしないと臆病で興奮した時に片足が抜けてしまう体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','セントバーナード・バーニーズ・ミックス犬',NULL,NULL,'pull multi','普段はおとなしいが興奮すると引っ張るセントバーナードとバーニーズ、ミックスの子犬にそれぞれ使い、どの子にも合ったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','トイプードル',NULL,NULL,'pull','3.3kgのトイプードルで、引っ張ると止まるようになったが、そこから前に進まなくなることもあり慣れを待っている体験。頭を通さずに着けられる点は楽だった。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk',NULL,NULL,NULL,'pull','使い始めの勢いよく走った時に派手に転んだが、その後は注意して歩くようになり、少し前を歩くもののグイグイ引くことはおさまった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk',NULL,NULL,NULL,'scared pull skin','ビビりで引っ張りの強い保護犬で、引く力が半分になった一方、脇が赤くなったためフェルトのカバーを付け、緩む胸の部分は縫い留めた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','グレートピレニーズ',NULL,NULL,'puppy pull','人や自転車を見ると走り出す7か月・33kgのピレニーズで、最初は着けるのに苦労したが、引っ張りが8割ほど減り片手でも制御できるようになった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','雑種',NULL,NULL,'pull sizing','15kgの雑種で、前側を一番小さくしてもまだ少し大きい。引き返す力は半分ほどで済むが、胸にリードを付けるのでたるむと地面に付きやすいという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/284187_10031274/1.1/'),
('petsafe-easy-walk','ゴールデンレトリバー','large',NULL,'pull skin','しつけ教室でも直らなかった1歳・31kgの大型犬（ゴールデン）が片手で持てるほどになったが、脇の下が擦れて赤くなるため当て布などの工夫が必要な体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=countryfield&page_key=ps-ewhbulk'),
('petsafe-easy-walk','ミニチュアピンシャー',NULL,NULL,'pull skin durability','ハーフチョークで首の毛が薄くなった6歳のミニピンで、興奮時以外は引っ張らなくなった。脇が赤くなる時があり、半年で胸の調整金具が緩みやすくなった体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=countryfield&page_key=ps-ewhbulk'),
('petsafe-easy-walk',NULL,'large',NULL,'escape','後ろに引いてハーネスを脱いでしまう30kgの大型犬の保護犬で、胴回りがしっかり固定され脱げることはなかった。緩みやすいという声を見て調整部を縫い留めた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=countryfield&page_key=ps-ewhbulk'),
('petsafe-easy-walk',NULL,NULL,NULL,'pull skin','脇にかなり食い込んでいるように見え、引っ張れない分いら立つのか歩くのをやめてじゃれついてくるようになり、うちの犬には合わないかもしれないと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=countryfield&page_key=ps-ewhbulk'),
('petsafe-easy-walk','ゴールデンレトリバー',NULL,NULL,'puppy trachea','上の2頭は引っ張り癖がすぐ直ったが、5か月の子犬では引っ張らないのに咳き込むことが多く、小さな体には合わないかもしれないと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=glv&page_key=pts-90'),
('petsafe-easy-walk',NULL,NULL,NULL,'pull','引っ張りの強さはハーフチョークを10とすると4ほど。胸にリードがあるので散歩中にリードを噛まれることがあり、長い散歩には別の道具と使い分けている体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=glv&page_key=pts-90'),
('petsafe-easy-walk','キャバリア',NULL,NULL,'pull','爪が削れて出血するほど引っ張っていた1歳・8.8kgのキャバリアで、動物病院で勧められて使うと引っ張りがほとんどなくなった体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=glv&page_key=pts-90'),
('petsafe-easy-walk',NULL,NULL,NULL,'skin','引っ張りは抑えられたが、服を着せても脇が擦れて赤くなり痛々しいため使用をやめたという体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=glv&page_key=pts-90'),
('petsafe-easy-walk',NULL,NULL,NULL,'pull','初めての補助具で犬も飼い主も最初は動きがぎこちなかったが、効果はすぐに表れたという盲導犬候補生の若い犬での体験（動画）。','public_experience_summary','https://www.youtube.com/watch?v=YnlGkGgGQJU'),
('curli-vest-air-mesh','ミニチュアダックスフンド',NULL,NULL,'escape trachea','以前のハーネスは抜けやすく、興奮して引くとむせていた6.7kgのミニチュアダックスで、Mがぴったり合い生地も丈夫だった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','チワックス・ポメックス',NULL,NULL,'puppy multi','2〜3kgの子犬2頭に2XSがちょうど良く、作りもしっかりしていたという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','チワワ',NULL,NULL,'escape pull','首抜けしやすいチワワで、このハーネスにしてから抜けたことがなく、引っ張り癖があっても苦しそうにしないため5回リピートしている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','黒豆柴',NULL,NULL,NULL,'体に当たる部分が柔らかい素材だけのものを探していた7.8kgの黒豆柴で、預け先で一日中着けっぱなしになることが多くても使いやすいと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','チワワ',NULL,'short','escape','スムースのチワワで、体にフィットしマジックテープで調整でき、抜けにくく軽いので繰り返し購入している体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','トイプードル',NULL,NULL,'sizing clothes','9kgのプードルで、新しいタイプのMは旧タイプのSと同じくらいきつくLに交換。新しいものは伸縮性が少ないように感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh',NULL,NULL,NULL,'durability','サイズ調整部分がマジックテープのため、ベルトとマジックテープが当たって擦れるところが少し気になったという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','チワワ',NULL,NULL,'sizing clothes','胸回り36cmのチワワにXSでマジックテープの範囲ぎりぎり。冬に厚手の服を着るときつく、マジックテープの持ちも気になるという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','マルチーズ×チワワ',NULL,NULL,'clothes','冬服の上から使えるものを探していた3.4kgのマルチワにSがちょうど良く、ごわつかずしなやかだが丈夫で色違いでも購入した体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','ポメラニアン×チワワ',NULL,NULL,'sizing','毛が多く胸板が厚い3.1kgのポメチワにXS。調整幅は広くないので、胸板が厚い犬は1サイズ上も検討するとよいと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh',NULL,NULL,NULL,'sizing','旧タイプと同じSを選んだが新しいものは全体に少し小さく、生地も硬く薄くなったように感じたという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','トイプードル',NULL,NULL,'sizing','肩ががっしりし胸板の厚い1.9kgのトイプードルで、3XSではマジックテープがほぼ留まらず2XSに交換。着脱がとても楽だった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/1.1/'),
('curli-vest-air-mesh','スピッツ',NULL,NULL,'durability','8kgのスピッツにL。柔らかく、濡らしてクールベストのようにも使え、約1年使って少し伸びてきたため買い替えた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/2.1/'),
('curli-vest-air-mesh','トイプードル',NULL,NULL,'sizing','3.6kgのトイプードルにXSは胸がきつそうでSに交換。胸のマジックテープ以外はあまり調整がきかないのでサイズ選びが大事だと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/2.1/'),
('curli-vest-air-mesh','ポメラニアン',NULL,NULL,'easy-on','3.5kgのポメラニアンにS。他のハーネスより毛が付きにくく、これまで手こずっていた着脱が簡単になった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000879/2.1/'),
('curli-vest-air-mesh','チワワ×スピッツ',NULL,NULL,'puppy escape','4か月の子犬にXS。マジックテープが弱めで気づくと浮いており、後ずさりした時に抜けて危なかったため、強いテープに付け替えると決めた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000879'),
('curli-vest-air-mesh','チワワ2頭',NULL,NULL,'multi escape','胴囲38〜39cmのチワワ2頭にS。装着時に強く引いて試しても抜けず、引いた時の負担も少ないと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000879'),
('curli-vest-air-mesh','トイプードル',NULL,NULL,'puppy','4か月・1.6kgの子犬で、外れて事故にならないよう軽くて頑丈なものを探し、サイズがぴったり合ったという体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000879'),
('hakusan-zero-harness','トイプードル',NULL,NULL,'sizing clothes easy-on','首が細く胴回り40cmほどの5.8kgのトイプードルにXXSがぴったり。首と胴を別々に調整でき、頭を通して両脇のバックルを留めるだけなので楽な体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness','ミニチュアダックスフンド',NULL,NULL,'clothes escape','5kgのミニチュアダックスにXXS。冬服の上からでも調整の余裕があり、抜けることもなく、裏のクッションも良かった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness','トイプードル',NULL,NULL,'trachea easy-on','3.3kgのトイプードルで散歩時のむせがなくなり、足を上げずに着脱できるので嫌がらず、散歩も楽しそうになった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness','柴犬',NULL,NULL,'dislike-on','9kgの柴犬で、最初はとても嫌がったが今では慣れてすんなり歩けているという体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness','イタリアングレーハウンド',NULL,NULL,'sizing skin','首が細いイタグレで首回りは一番細くしても余裕があるが、そこそこ引っ張っても左右にずれず脇にも当たらない。心配なので首輪と併用している体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness','柴犬',NULL,NULL,'trachea','気管支炎で咳が出るため獣医師に胸元がY字のものを勧められ、11.5kgの柴犬にS。クッションで負担は少なそうだが、思ったよりごつさを感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness','柴犬',NULL,NULL,'puppy dislike-on','ハーネス嫌いで困っていた6か月の柴犬が、ようやく嫌がらずに着けてくれるようになった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness',NULL,NULL,NULL,'durability','柔らかく肩の動きを妨げない作りで子犬やシニアにも向きそうだと感じた一方、半年を目安に買い替えるよう案内されており、素材からもそのくらいの強度だと思った体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/1.1/'),
('hakusan-zero-harness','サモエド',NULL,NULL,'sizing','21kgのサモエドに胸囲からLを選んだら大きく、Mに交換してちょうど良くなった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness','ジャックラッセルテリア',NULL,NULL,'escape sizing','8.5kgのジャックラッセルで、XSを一番きつくしても緩めになり、しばらくすると抜けるようになったためXXSに買い替えた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness','トイプードル',NULL,NULL,'escape trachea','2.8kgのトイプードルにTinyを一番きつく調整して使用。着脱のたびにベルト調整が必要で面倒だが、後ずさりしても外れなさそうで、以前のようなむせも減った体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness','フレンチブルドッグ',NULL,NULL,'sizing clothes','12kg弱のフレブルにXSを最大に伸ばしてぴったり。薄い服ならぎりぎりで、冬のもこもこ服の上からは無理だった体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness','ミニチュアピンシャー',NULL,NULL,'puppy escape skin','服を上手に脱いでしまう10か月・3kg弱のミニピンで、肌も弱いためハーネスを色々試しており、初日の散歩では良さそうだと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness','フレンチブルドッグ',NULL,NULL,'skin','前のハーネスで皮膚が荒れた8.5kgのフレブルにXS。体側の素材が柔らかく擦れもなく、外れる心配もないと感じた体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness','ゴールデンレトリバー',NULL,NULL,'escape','32kgのゴールデンで、首を調整しても少し緩いが抜けることはなく安心して使えている体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness',NULL,NULL,NULL,'sizing escape','首と胴の差が大きい16kgのハウンド系の犬で首はぶかぶかになり、背中の持ち手も手を通しにくいため、首輪と併用している体験。','public_buyer_review_summary','https://review.rakuten.co.jp/item/1/212247_10000685/2.1/'),
('hakusan-zero-harness',NULL,NULL,NULL,'escape','突然の後ずさりで首抜け事故があった11kg弱の犬にXS。後ずさりした時にリードの付け根がめくれ上がりひやっとしたが、首と胴をぴったり合わせていれば抜けないと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685'),
('hakusan-zero-harness',NULL,NULL,NULL,'scared escape trachea','車や物音に驚いて急に引いたり後ずさりしたりする1歳・14kgの保護犬で、前のハーネスのようにむせることがなく、体に沿うので後ずさりしても抜けなかった体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685'),
('hakusan-zero-harness','フレンチブルドッグ',NULL,NULL,'skin','脇の下に帯が来るハーネスで毛が擦れて剥げたフレブルに替え、脇に帯が来ず短毛にも優しい一方、飼い主が前に出て促す時にリードの付け根がめくれて安定しにくいと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685'),
('hakusan-zero-harness','コーギー',NULL,NULL,'durability','短足でお腹側が汚れやすく頻繁に洗う10kg弱のコーギーで、半年過ぎから擦り洗いする部分の生地が薄くなったが、切れたり外れたりはなかった体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685'),
('hakusan-zero-harness','シーズー',NULL,NULL,'trachea clothes','気道の圧迫が気になっていた9.5kg以上のシーズーで、冬は服の上から着けるためSを選び、圧迫感が軽くなった体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685'),
('hakusan-zero-harness','ヨークシャーテリア',NULL,NULL,'puppy escape','体が柔らかく服もすぐ脱いでしまう11か月のヨーキーが、前のハーネスを原っぱで脱いでしまったため探し、このハーネスは良かったという体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685'),
('hakusan-zero-harness',NULL,'large',NULL,'neck','年齢が上がってきたため首輪から切り替えた27kgの大型犬にLがぴったり。素材が柔らかく、スムーズに歩いてくれた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685'),
('hakusan-zero-harness',NULL,'small',NULL,'trachea sizing','気管虚脱と心臓病があり気管に優しく抜けにくいものを探した小型犬で、一番小さいサイズでも少し大きく、リードを付けると首まわりがもたつくと感じた体験。','public_buyer_review_summary','https://shopping.yahoo.co.jp/review/item/list?store_id=1stdogcafe&page_key=10000685')
)
INSERT INTO reviews(product_id,dog_breed,dog_size,coat_type,needs,summary,source_type,source_url)
SELECT n.product_id,n.dog_breed,n.dog_size,n.coat_type,n.needs,n.summary,n.source_type,n.source_url
FROM new_reviews n
WHERE NOT EXISTS (
  SELECT 1 FROM reviews r
  WHERE r.product_id=n.product_id
    AND r.summary=n.summary
);

SELECT COUNT(*) AS dog_harness_product_count FROM products WHERE category='dog-harness' AND active=1;
SELECT COUNT(*) AS dog_harness_review_count FROM reviews r JOIN products p ON p.id=r.product_id WHERE p.category='dog-harness' AND p.active=1;
